#!/bin/bash
BASE=$HOME/webrtc
[ ! -d $BASE ] && mkdir -p $BASE && cd $BASE && fetch webrtc_android
cd $BASE && gclient sync && gclient runhook
if [ ! -d $BASE/src/third_party/android_tools/sdk/extras/google/google_play_services ]; then
	echo "y" | $BASE/src/build/install-android-sdks.sh
	echo "y" | $BASE/src/build/install-build-deps-android.sh
	gclient sync && gclient runhook
fi

cd $BASE/src
. build/android/envsetup.sh
ninja -C out/Release AppRTCDemo
